### ISSUE TITLE
Improve GeoNames Location functionality

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1277]
- [x] Would like pop-out link to the GeoNames map on the show page. For example, [this record](https://ir.library.oregonstate.edu/concern/technical_reports/47429g118) is for Elk River. It would be more helpful if there was an external link to the [GeoNames map](http://www.geonames.org/maps/google_42.793_-124.526.html).

- [x] Could the name include more location details? There are many hits for Elk River; it would be better if the show page included more of the details in GeoNames, like the county, state, and country. (Also less nationalistic.)

- [ ] Instead of lengthy searching & cross-referencing on GeoNames, I'd like to be able to locate the URI on GeoNames and add it to the search box.

**Comment by wickr** [comment]
Some thoughts: 
* I don't recall if Geonames includes a direct map URL in it's API response, but you get basically the same thing with this URL which should be in there: http://www.geonames.org/5725428/elk-river.html

* Yes, like Brandon said this is all doable. Right now, the typeahead label is different from what gets saved to Solr. I think they should match exactly. Once this code change is live, will definitely need to reindex everything (or at least everything with a Location/geonames URI).

* I'd be surprised if we can easily add an option to directly paste a URI into the Location box without conflicting with typeahead search. Further, the URI we really want ( `http://sws.geonames.org/5879092/` ) isn't usually exposed in the Geonames web URI, so what exactly are expecting to be input?. If typeahead isn't doing the job, I think we should look at why exactly that is and not make the form also take a URI for this.

**Comment by simholt** [comment]
@wickr About the third point -- I sometimes have to go to the GeoNames site to check the exact ID since many places share names. The search bar shows the same results, so I have to go to the GeoNames search results and see which result is correct. (This happens most often with bodies of water.)

![depoe bay](https://user-images.githubusercontent.com/33705514/40069303-bcc25d8a-581f-11e8-84c3-72c71dc8b54e.png)
![count them](https://user-images.githubusercontent.com/33705514/40069307-bfd1d992-581f-11e8-81b2-3f0b947219db.png)

It would be nice if I could just pull the URI (the ID number is shown below) and drop that in.

![geonames_org](https://user-images.githubusercontent.com/33705514/40069313-c249c586-581f-11e8-9ac8-d7e1b6e11f63.png)

TBH, this is more of a wish list issue, along with enabling SA to accept URI drops in other fields.

An alternative: What about enabling the search box to return Feature Classes? Would that be too crowded?

![feature class](https://user-images.githubusercontent.com/33705514/40069523-796b80e2-5820-11e8-9023-1dd42c30c781.png)

**Comment by wickr** [comment]
@simholt Ah, yes, I often do similar searching for OD. I think Feature Class would be a good addition to the typeahead display. That could even include the Geonames ID for additional verification.

@vantuyls yeah I think the direct URI paste stuff should at least be a separate ticket.

**Comment by straleyb** [comment]
@vantuyls @simholt @wickr  Ill go ahead and begin breaking these down into separate tickets. If you all want to go through them and double check whether or not they cover all the points from this ticket, then I can get rolling on knocking some of them out.

**Comment by simholt** [comment]
@wickr @vantuyls @straleyb 

FYI: GENERAL URI functionality already has a ticket: #1328

**Comment by straleyb** [comment]
Covered by #1443
