### ISSUE TITLE
Deploy Hyrax 2.1.0 to production

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1368]
- [x] Update hyrax210 branch to hyrax 2.1.0 after it is released
- [x] Merge `hyrax210` branch to master
- [x] Deploy to staging server to verify functionality
- [x] Deploy to production
  - [x] Update local_env.yml on server with appropriate environment variables
    - [x] fedora url should be like `http://servername/fcrepo` without the trailing `/rest`
  - [x] Deploy application
  - [x] Execute rake tasks (Default Collections, and Collection Migration sections) https://github.com/samvera/hyrax/releases

**Comment by revgum** [comment]
was deployed in early June
