### ISSUE TITLE
Student/Employee and Student Type context 

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1426]
OSU has a "Persons" API that can be used to query if a user is a student or employee. I've opened a line of communication in getting the API extended to include if the student is a graduate or undergraduate. 

The idea here is that we could extend the User model to include a few fields about the user;
- [x] `api_person_type:string` : Employee or Student
- [x] `api_student_type:string` : Null, Undergraduate, or Graduate
- [x] `api_person_updated_at:datetime` : The previous datetime that the API was queried for the persons details

Some thoughts around throttling the frequency we use the API to query these details. 

- When a user logs in, evaluate if a configurable period of time has elapsed and if the API should be queried to update the status of the person. Maybe this configuration should be a couple months or so?
- Depending on the previous evaluation, query the API and update the Users record.

**Comment by simholt** [comment]
Done
