### ISSUE TITLE
Featured Researcher Manager

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1471]
Implement a manager on the Featured Researcher content block tool that allows:
- [ ] adding multiple featured researchers as independent content blocks
- [ ] removing featured researcher blocks
- [ ] featured researcher on homepage should cycle through featured researchers on the content blocks
