### ISSUE TITLE
Implement ordering on Creator metadata field

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1500]
Approach is to make Creator a nested resource with type, order, and value as nested elements. Things to consider:
- [x] order is an integer
- [x] 0 index
- [x] value is a string
- [x] order validation: no duplicate index number
- [x] reindex order on save/submit
- [x] UI to reorder creators - similar to what we see on homepage for featured researcher, but can well-handle 35 or more creators [example](https://ir.library.oregonstate.edu/concern/articles/8910jw33p)
- [x] javascript validation in the UI (e.g. to prevent duplicates)?

**Comment by vantuyls** [comment]
related sub-issues:
https://github.com/osulp/Scholars-Archive/issues/1542
https://github.com/osulp/Scholars-Archive/issues/1543
https://github.com/osulp/Scholars-Archive/issues/1544
https://github.com/osulp/Scholars-Archive/issues/1545

**Comment by luisgreg99** [comment]
fixed by https://github.com/osulp/Scholars-Archive/pull/1554
