### ISSUE TITLE
Google Scholar meta-tags improvements

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Scholars-Archive#1916]
### Descriptive summary

We have received suggestions for improvement in Google Scholar meta-tags for ScholarsArchive. These updates will help Google Scholar get the metadata needed for proper indexing.

- [ ] 1. Implement `GoogleScholarHelper.citation_publication_date` to properly format `date_uploaded`, which is a fallback when `date_created`, `date_issued`, and `date_accepted` are not available for `citation_publication_date` meta-tag in [app/views/shared/_citations.html.erb](https://github.com/osulp/Scholars-Archive/blob/master/app/views/shared/_citations.html.erb). 
- [ ] 2. Update shared/_citations partial to exclude empty meta-tags from view [app/views/shared/_citations.html.erb](https://github.com/osulp/Scholars-Archive/blob/master/app/views/shared/_citations.html.erb) when not available.
- [ ] 3. Update [robots.txt](https://github.com/osulp/Scholars-Archive/blob/master/public/robots.txt) to allow `Googlebot` to access `/catalog` so that it can access URLs for repository items as well.
- [x] 4. Run SOLR query to find out if any works are missing a date in `date_created`, `date_issued`, and `date_accepted`.
- [x] 5. Run SOLR query to find out if there are any dates in the form of date intervals like "2017-12-01/2019-12-01", and check with metadata group to see if we can use the start date in the interval for `citation_publication_date` meta-tag.

### Expected behavior

- For checklist item (1) in Descriptive summary above, `citation_publication_date` expects dates in the formats "2017/12/01”, "2017/12", "2017", as well as ISO 8601 with the exception of date intervals like "2017-12-01/2019-12-01".
- For checklist item (2), we have an example where `citation_issue`, `citation_firstpage`, and `citation_lastpage` are still being rendered when the content values are blank:
```
view-source:https://ir.library.oregonstate.edu/concern/articles/2n49t2687?locale=en    
<meta name="citation_issue" content=""/>
<meta name="citation_firstpage" content=""/>
<meta name="citation_lastpage" content=""/>
```

- The expectation for checklist item (2) is that if we don't have the information, no meta-tags for these fields would be better than empty metatags.

### Current behavior

- [robots.txt](https://github.com/osulp/Scholars-Archive/blob/master/public/robots.txt) is disallowing /catalog for Googlebot. It's preventing the crawler from accessing the browse interface to find items. 
- Fields `date_created`, `date_issued`, and `date_accepted` might have invalid format
- Other citations meta-tags like citation_issue, citation_firstpage, and citation_lastpage are being rendered when blank

### Related work

https://github.com/osulp/Scholars-Archive/pull/1884

**Comment by simholt** [comment]
Progress on part 5:
I located the items with ranges in `date_created`, `date_issued`, and `date_accepted` and either moved that information to `date_collected` or deleted it. I also updated `date_issued` with correct info as needed.

I created a bulk change list to remove duplicate date-related fields. The `citation_publication_date` meta-tag  should default to `date_issued` as needed.
