### ISSUE TITLE
Support for linked external resources

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2549]
### Descriptive summary

SA needs better support for "Link-only" records that point to external resources without a copy of the file included. This is currently technically possible in SA, but the UX is poor.

Use cases:
- OA scholarly articles
    - Particularly, Springer Nature is now providing authors with a view-only link to their articles, which are allowed to be shared in IRs but can't be downloaded. https://www.springernature.com/gp/researchers/sharedit 
- Datasets through external providers 
    - Could help with handling larger datasets or campus data hosting services if available

Would like a discussion about whether this would require a new work type, or if it could be an option available on existing WTs (especially Article, Dataset).

### Expected behavior

- A specialty linked-document icon is displayed in the thumbnail space, similar to:

![image](https://github.com/osulp/Scholars-Archive/assets/17655103/da5b403c-64cf-4301-bdc9-8ff5a2443907) (source: https://thenounproject.com/icon/document-5725414/)

- Instead of "Download PDF" below thumbnail space, use "View online" (consistent with catalog language)
- Resource link opens in a new window
- Instead of "There are no publicly available items in this [Worktype]", the "Items" section at the bottom of the show page shows something like "This item is available from an external website: [Link]."
- Enhancement - Link checker that reports dead links
- If a new work type is needed:
    - Admin deposit, not self-deposit (however, library student workers need to be able to deposit)
    - Should require a DOI or other persistent identifier
    - Need to determine a metadata field list 

### Actual behavior

See for example: https://ir.library.oregonstate.edu/concern/articles/db78tj75f

**Comment by CGillen** [comment]
Some initial thoughts:

- Can this be a part of FileSets?
  - This will allow the functionality on any work type
  - This ties into the display functionality well
  - Can/Should we reuse some oEmbed work from OD2?
  - This could introduce a lot of complexity to the FileSet workflow throughout the whole project
  - Could make problems for indexing and characterization
- How would this work as a new work type?
  - Make FileSet upload unavailable?
  - Add a new metadata field for the link?
  - How does display work? Is it more complex than FileSet?

**Comment by carakey** [comment]
@CGillen 

I'm not opposed to having it as part of FileSets, and I can imagine this working a lot like the OD oEmbed from the depositor's perspective -- so either a file is uploaded or an external resource link is added. I do think that there are some work types where we don't want this available, though - any of the standard student-submitted works, in particular, and GTDs especially. 

I don't think we're trying to incorporate any display or characterization of the external resource itself. Basically it's an object with no FileSet attached (and we already have a number of those!), but enhanced so that the link is clearer and with a specialized thumbnail. 

What kind of problems do you see for indexing and characterization?

Michael originated this request and I'd like to get his thoughts, once he's back from vacation.

**Comment by shieldsb** [comment]
@boockm When you have time, could you take a look at the comments from Corey and Cara above.

**Comment by carakey** [comment]
> [@boockm](https://github.com/boockm) When you have time, could you take a look at the comments from Corey and Cara above.

@shieldsb Michael sent me a note in email: 

> You nailed it in your response. I don't have anything to add.

**Comment by lamtu1** [comment]
Hi @carakey, as I am looking through this, I was wondering with some questions below:

1. Would you like to have `no preview available` as a thumbnail or would you like an icon (similar to what you show in the ticket) to display in the `work show page`?
2. Would you like just to have a textbox to paste in the link in the `create/edit form` that would be a part of the FileSets?
3. Who would have access to do this? (admin, student, etc...) and which work type would we only limit it to?
4. I saw that we have a `question` tag still on this ticket and was wondering if this ticket need more refining before work can be done on?

Thank you!

**Comment by carakey** [comment]
Hi @lamtu1. 
Are you looking at this as part of filesets, as opposed to a new work type? I think that's a critical piece to figure out. I'm not sure it was settled but I think it's the direction we were leaning, potentially with some of the oEmbed work from OD. So assuming the fileset route, I'll try to answer these:

> 1. Would you like to have no preview available as a thumbnail or would you like an icon (similar to what you show in the ticket) to display in the work show page?

I prefer the icon thumbnail as shown. 

> 2. Would you like just to have a textbox to paste in the link in the create/edit form that would be a part of the FileSets?

If I'm understanding this question, then I think yes -- similar to the UI in OD for the oEmbed option, near the bottom of this screenshot:

![image](https://github.com/osulp/Scholars-Archive/assets/17655103/ade99253-6756-400f-8743-dc1d9261caf1)
 
> 3. Who would have access to do this? (admin, student, etc...) and which work type would we only limit it to?

* If we make this part of FileSet, can we still impose limits on it by role-based permissions and/or work types? That will be a big determining factor. 
* If it is role based, the specifications above (for the new worktype route) should work -- admins and library student workers. 
* If it is worktype based, then we do NOT want to allow this on any student submitted works. So not allow on (1) Graduate Thesis Or Dissertation, (2) Graduate Project, (3) Undergraduate Thesis Or Project, or (4) Honors College Thesis

> 4. I saw that we have a question tag still on this ticket and was wondering if this ticket need more refining before work can be done on?

The main thing is still whether we are going ahead with this as a part of filesets or creating a new worktype. I was hoping for more clarification on @CGillen's comment -- what problems we anticipate with regard to workflow complexity, indexing and characterization?

**Comment by CGillen** [comment]
Those were some high-level thoughts without much of a concrete issue tied to the bullets.

I believe my thinking about added complexity is that there is A LOT of code dedicated to oEmbed in OD2 already. Picking & choosing what needs to come over and what doesn't and what needs re-written is a lot of breakable points.
At the time I was also thinking there could be issues we haven't faced with parts of Hyrax assuming there are files on a fileset, particularly in the actor stack where the whole fileset goes through a gauntlet of "stuff" while it's saving/updating. Obviously we have faced this in OD2 so it's a moot point

I was thinking indexing & characterization might be something you might wanted based on the linked resource, particularly for audits and reporting by types of content/formats. Finding the associated files with the linked resource would be impossible so we wouldn't be able to add any of that metadata or you'd have to enter it all by hand. But it sounds like you're ok with no metadata for these filesets? That shouldn't be a problem then. I don't know if this will skew audits or reporting though?
And again, the thought that Hyrax assuming a file existed would break things in characterization crossed my mind, but I clearly didn't have all my marbles together

**Comment by carakey** [comment]
Thanks @CGillen. I think the functionality here is a lot simpler than oEmbed. We want basically to have SA be an alternate discovery and access point for some resource (an article, a dataset) that's located elsewhere. The resource doesn't need to be embedded for display in SA -- just linked and represented with a (descriptive) metadata record. Basically I'm thinking of it as, the link **is** the resource, so we don't need the characterization information for the resource. 

The few works we have now that do this job, of linking to an external resource, don't have filesets at all. In [this example](https://ir.library.oregonstate.edu/concern/articles/db78tj75f) the work metadata refers to the article linked through the DOI field, but it isn't super obvious to a user and the overall messaging is mixed ("Can I get this thing or not?"). 

Maybe I'm not being helpful. I think we're looking for a toggle, somewhere and somehow (because it's a different work type? because it uses a specialized metadata field? because it uses a different fileset option?), that tells Hyrax that this work gets displayed differently from other works in the ways described at the top of the ticket.

**Comment by lamtu1** [comment]
Hi @carakey , I have a list of questions to follow up on this ticket hoping you could answer:

1. I wanted to mention about the `characterization`, you mention in the comment that "`Basically I'm thinking of it as, the link is the resource, so we don't need the characterization information for the resource `". In this, when I was talking to Corey about it, he said that the `characterization` is in regards of the `FileSet` data as in like is it an image or many other properties need for characterization. He wonder do we need the `chracterization` for those link like for example going into the link website and determine what kind of fileset charcterization it is, or you think it is not necessarily in this case?

2. As I discuss the method with Corey, we are going down the route of `Fileset` so it will be available on all worktype, and we can limit it on the `worktype` base on what you mention above and we can modify if needed on the backend as well. But as we plan do this with the `FileSet`, I was wondering do you need the `URL to be store and be part of the metadata as Corey mention due to the problem of might be skew audits or reporting` & as implementing with FileSet, would you like to have a `predicate` for this new field in FileSet or none at all?

Thank you for taking your time reading through with this, I know it is a bit long but hope this bring more out to clarify some understanding.

**Comment by carakey** [comment]
We do not need to track remote files as if they are part of the repository. The audit I've been doing is for preservation risk assessment, and it won't be OSULP's responsibility to preserve remote items. 

So --
1: No, we do not need need to try to fetch info and characterize those files based on the external sites' data. If it's possible, maybe we could characterize the link itself, so for instance the characterization metadata would have something like `mimetype = text/uri-list` (I think). But none is okay.  

2: Ideally yes, a predicate would be super for longevity, compliance, etc. -- and for internal use, yes, it would be nice to be able to query and count the remote resource works. I was able to find a pretty exact match from [Rioxx](https://rioxx.net/profiles/v3-0-final/), `rioxxterms:ext_relation`:

> `rioxxterms:ext_relation` is used to convey external associations to related resources (i.e. external relations). Such relational associations will be scholarly resources hosted externally, i.e. outside of the direct custodianship of the repository asserting the relational associations

**Comment by carakey** [comment]
__QA (criteria based on ticket and Slack conversations):__

Creating work:

- [x] External resource link field is available on Files tab -- QA pass
- [ ] Only a link or a file may be added, not both -- QA fail, creates a broken work.
    - Entering both and saving results in "something is not working on our end" page
    - The work DOES get created, but it cannot be accessed
    - Instead could we make it so they are unable to submit if both files and external resource URL are included? 
- [x] External resource field is not available on student-submitted work types (GTD, Grad Project, Undergrad Thesis, HCT) -- QA pass
- [ ] Library student workers are able to create a link-only work
    - Verify with Kenna B

Editing or deleting external resource link after saving: QA fail. "Something is not working on our end" error when I click Edit from the Fileset. Unable to test this further.

- [ ] Link can be updated with same FileSet PID
- [ ] Link field cannot be left empty
- [ ] Fileset can be deleted

Show page display (when NOT logged in):

- [ ] Linked-document icon is displayed in the thumbnail space -- QA fail, thumbnail is not appearing
- [x] "View online" shows beneath thumbnail space -- QA pass
- [ ] Resource link opens in a new window -- QA fail.
    - Yes it opens in a new window using "View online" link under thumbnail space
    - Should also open in a new window from the "Items" section link 
- [x] "Items" section on show page shows "This item is available from an external website: [Link]" -- QA pass

Metadata:

- [ ] External resource has predicate `rioxxterms:ext_relation` -- Unable to test
    - I'm not able to get the NT file for the fileset the way I usually do, by just adding ".nt" after the PID in the address bar - I get either a 406 (with the "parent" part of the URL included) or the "Oops" error message (if I strip the "parent/PID/" part). 

@lamtu1 still some kinks to work out.

**Comment by carakey** [comment]
@lamtu1 QA'd again after Slack message and updated my prior comment. 

It is successfully blocking me from trying to add both an external resource and a file.

The thumbnail is appearing now in the upper area of the work show page, but can we do anything about this? 

![Image](https://github.com/user-attachments/assets/9a38ecc4-ee36-49fd-96a6-b83bbb522d5d)

**Comment by lamtu1** [comment]
> The thumbnail is appearing now in the upper area of the work show page, but can we do anything about this?

Yes this can be done, I just need to hook it up with the `thumbnail_path` for it to display and on top of it, I will get the other fix as well

**Comment by carakey** [comment]
Moving this to IN PROGRESS - but add comments here when it's ready to QA again.

**Comment by lamtu1** [comment]
@carakey This is ready to QA, can I have you go on staging and start the whole process from the beginning with the new work and test from there? When you get a chance, thank you!

**Comment by carakey** [comment]
Still some issues with Edit/Versions and with the underlying metadata. 

I would also like to update the help text on the Work/Files tab for the External Resource URL field to discourage overuse and to make it clear that SA is not going to go fetch and deposit that item. Let's say: "To create a ScholarsArchive record that links to a work in another location, add an External Resource URL here. The location of that work must be reasonably stable, so a DOI or other persistent URL is strongly encouraged. Use one URL here or the files above, but not both." 

__QA__

_NEW Test work: https://ir-staging.library.oregonstate.edu/concern/defaults/rb68xc071_

Creating work:

- [x] External resource link field is available on Files tab -- QA pass
- [x] Only a link or a file may be added, not both -- QA pass
- [x] External resource field is not available on student-submitted work types (GTD, Grad Project, Undergrad Thesis, HCT) -- QA pass
- [ ] Library student workers are able to create a link-only work
    - Verify with Kenna B

Editing or deleting external resource link after saving: QA fail. "Something is not working on our end" error when I click Edit from the Fileset. 

- [x] Link title can be updated on fileset edit page
- [ ] Versioning from fileset edit page is EITHER functional for replacing the URL in the fileset OR is disabled -- QA fail. 
    - The Versions tab has file upload options and no URL field options. 
    - The Versions tab appears to let me upload and save a file. 
    - After saving, that uploaded file is nowhere to be found, except it keep the uploaded filename as the fileset title. 
    - The external resource URL is unchanged on the work page.  
- [x] Link can be updated with same FileSet PID -- QA pass, minimally 
- [x] Link field cannot be left empty -- QA pass
- [x] Fileset can be deleted -- QA pass
- [x] After deleting an external resource fileset, a new fileset can be created, with a new PID (whether external or normal file) -- QA pass

Show page display (when NOT logged in):

- [x] Linked-document icon is displayed in the thumbnail space -- QA pass
- [x] "View online" shows beneath thumbnail space -- QA pass
- [x] Resource link opens in a new window -- QA pass
    - [x] Using "View online" link under thumbnail space
    - [x] Using "Items" section "Click here" link 
- [x] "Items" section on show page shows "This item is available from an external website: [Link]" -- QA pass

Metadata:

- [ ] External resource has predicate `rioxxterms:ext_relation` -- QA fail. 
    - There is no `rioxxterms` predicate found in the NT metadata. 
    - The only RDF statement for the fileset that appears to be related to the external resource URL is `<http://fcrepo.sa-test.svc.cluster.local:8080/fcrepo/rest/staging/2v/23/vt/61/2v23vt61d> <http://purl.org/coar/resource_type> "https://en.ƒ.org/wiki/Lorem_ipsum" .` -- which is garbage... That `en.f.org` doesn't seem to be a resolvable URI, and it certainly isn't a COAR resource_type.

**Comment by lamtu1** [comment]
@carakey You can start testing the `FileSet` edit page and update the QA list if you like. It should be up on staging, and currently just trying to dive deep into `rioxxterm` today to get that up.

**Comment by carakey** [comment]
@lamtu1 The FileSet edit page seems to be working well. But, now if I try to change the URL from the Work edit page, I get the "Something is not working on our end" error.

**Comment by lamtu1** [comment]
That's weird, I will go get a chance to look into it and see what seems to be the problem for work edit page.

**Comment by lamtu1** [comment]
`QA:` @carakey I updated the `property`, so for QA, I would love to start fresh with a new work and go through the list again to test, and I couldn't find where the edit page for work edit is broken. I will reach out to you to maybe sit down and go through your step process when you are QA this so I can get sense of what is going on, on staging on your end.

**Comment by carakey** [comment]
QA TL;DR -- much closer!  

1. editing = pass 🎉 
2. metadata predicate seems slightly off
3. missed the ask last time about updating the help text on the URL field

----- 

# QA

_NEW Test work: https://ir-staging.library.oregonstate.edu/concern/articles/9p2909531_

## Creating a work:

- [x] External resource link field is available on Files tab -- QA pass
- [ ] External resource link field has clear instructions (updated text in comment above) -- QA fail.
    - Please update the `External Resource URL` field on the `Files` tab to read (instead of "Add an External Resource URL here. Use one URL here or the files above, but not both."):
    > "To create a ScholarsArchive record that links to a work in another location, add an External Resource URL here. The location of that work must be reasonably stable, so a DOI or other persistent URL is strongly encouraged. Use one URL here or the files above, but not both." 
- [x] Only a link or a file may be added, not both -- QA pass
- ~External resource field is not available on student-submitted work types (GTD, Grad Project, Undergrad Thesis, HCT)~ -- Did not re-check at this time, I assume it's still fine
- [ ] Library student workers are able to create a link-only work
    - Verify with Kenna B (out of office until ~September 25)

## Editing or deleting external resource link after saving: 

### QA process, Step 1

Access Fileset edit page from `FileSet landing page` >> "Edit this File" button AND/OR from `Parent Work landing page` >> Items section >> dropdown >> Edit. From here: 

- [x] Link **title** can be updated on fileset edit page 
- [x] Link can be updated on fileset edit page 
- [x] Versioning from fileset edit page is EITHER functional for replacing the URL in the fileset OR is disabled (yes, disabled)
- [x] Updated fileset keeps the same FileSet PID
- [x] Link field cannot be left empty

### QA process, Step 2

Access Work/Files edit page from `Parent Work landing page` >> top right >> "Edit" button to get to work edit page; go to Files tab. From here:

- [x] External Resource URL appears in field on work/files edit page.
- [x] Link can be updated on work/files edit page << _This is where I was getting an error last time; seems like it's working now._

### QA process, Step 3 

Either from the `FileSet landing page` >> Delete button OR from the `Parent Work landing page` >> Items section >> dropdown >> Delete:

- [x] Fileset can be deleted 
- [x] After deleting an external resource fileset, a new fileset can be created, with a new PID (whether external or normal file) 

## Show page display (when NOT logged in):

- [x] Linked-document icon is displayed in the thumbnail space 
- [x] "[View Online]()" shows beneath thumbnail space 
- [x] Resource link opens in a new window 
    - [x] Using "[View Online]()" link under thumbnail space
    - [x] Using "Items" section "[Click here]()" link 
- [x] "Items" section on show page shows "This item is available from an external website: [Click here]()" 

## Metadata:

- [ ] External resource has predicate `rioxxterms:ext_relation` -- Almost there, but the predicate still needs a slight update (I think). 
    - I do see a plausible RIOXX predicate, but I see that it does not resolve to a legitimate resource in a browser. If we add a `#` before the term name, though, it does resolve. I also think we should drop the "docs" from the predicate; this still loads the schema page and may be more persistent. 
    - i.e. the current string is `http://docs.rioxx.net/schema/v3.0/rioxxterms/ext_relation` but I believe it should read `https://rioxx.net/schema/v3.0/rioxxterms/#ext_relation`

**Comment by lamtu1** [comment]
@carakey Since I have to update the `property` again, we need to QA this with a start on a new work again for it and can't edit on a work that is already on there since it is a new `property` update.

**Comment by carakey** [comment]
@lamtu1 I created a new item but there was no change in the RIOXX property. The help text also has not been updated. Maybe this wasn't actually ready for QA?

**Comment by carakey** [comment]
QA pass and ready for prod; let's still get both Michael and Kenna B to take a look before closing the ticket.

**Comment by carakey** [comment]
It seems `rioxxterms:ext_relation` RDF statements are not appearing in existing linked external resource works. The functionality otherwise seems fine, as far as linking to the resource and displaying the appropriate text and thumbnail, but the URL is not being stored with the metadata. 

We need to restore this predicate as part of linked external resource works. It needs to appear on both new external resource items and existing ones. 

- - - - -

Sagan came across an External Resource item and was asking how many are in the system. I figured the `ext_relation` predicate would be a way to locate these -- but as I looked at the example Sagan provided, it does not have the `ext_relation` statement in the NT, nor any occurrence of the destination URL in the NT or Solr metadata at all.

The example Sagan found is here: https://ir.library.oregonstate.edu/concern/articles/8w32rf54f

A couple more examples, also not showing an `ext_relation` statement: 

- https://ir.library.oregonstate.edu/concern/articles/h702qc90b
- https://ir.library.oregonstate.edu/concern/articles/76537630r

**Comment by carakey** [comment]
Hm, you're right, I do see it in the fileset NT, but still nothing in SOLR for the FileSet. That's what I'm after -- having them get indexed, whether it's on the work or fileset, as a way to be able to search for / otherwise identify these type of objects.
