### ISSUE TITLE
2024 Annual Preservation Assessment

### ISSUE THREAD

**Issue by carakey** [osulp/Scholars-Archive#2591]
During the CoreTrustSeal certification, we committed to and described specific actions we would take annually to assess preservation needs for ScholarsArchive@OSU, especially with regard to the file formats we store. 

See #2472 for 2023 assessment work, with report [here](https://library.oregonstate.edu/sites/default/files/2023_saosu_preservation_assessment_report.pdf)

- [x] Review/address fixity reports
- [x] Inventory file formats currently in SA (using Solr)
- [x] Review/update the [preferred file formats guide](https://guides.library.oregonstate.edu/Scholars-Archive/PreferredFileFormats)
- [x] Review/propose updates to the [SA preservation policy](https://wiki.library.oregonstate.edu/confluence/display/RP/ScholarsArchive@OSU+Policies#ScholarsArchive@OSUPolicies-PreservationPolicy)
- [x] Update and polish procedures for continuing annual assessments
- [x] Produce a brief report

The target time period for this work is April 29-May 3, 2024, which is designated as Preservation Week by ALA Core. This is not concurrent with any LIT ScholarsArchive workcycle. Relevant information will be shared here as the assessment progresses.

**Comment by carakey** [comment]
The Preservation Assessment Report is published on the library homepage at https://library.oregonstate.edu/sites/default/files/2024_sa_preservation_assessment_report.pdf.

- Fixity: No new concerns were identified or work completed during the assessment. Fixity reports have had attention throughout the year. Related open tickets are #2568, #2571 and #2572. Monthly tracking data is in the SA Google Drive ([link](https://docs.google.com/spreadsheets/d/1uP2AKpNssG_4ldaIMWdyL21UQKn7Q3aSVgUYSZ2JDJ8/edit#gid=587006759))
- Inventory:  Complete file format inventory data is in the SA Google Drive ([link](https://docs.google.com/spreadsheets/d/1GUY-jjCaObxC7d68Tx2Y3wqy9SD7TOQeDlj0jeHWNEo/edit#gid=2031904671)). Far fewer fileset errors showed up since the 2023 assessment, and most are repeats that are already ticketed including #2530 and #2491; 7 new problematic filesets were manually corrected; 2 new errors will be ticketed. Also still unable to include information about contents of torrent or container files, see #2569. 
- Format Recommendations: [Updated version published](https://guides.library.oregonstate.edu/c.php?g=708682&p=8342195). One new format (.ipynb) was added and minor other updates were made to the table. A changelog is included.
- Policy: No changes were recommended this year.
- Procedure doc: Available in the SA Google Drive [(link)](https://docs.google.com/document/d/1udSdEP_BLf4Cgoym13N1U3roJl1SK-5FWb6sgaQyBa4/edit#heading=h.pavgtsuenb6x)
