### ISSUE TITLE
[Bulk Migration] Make Bag Ingest Work in SA@OSU

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#404]
Major Steps that Need to Happen:
- [ ] #429 Hybag gem, update to Fedora 4
- [ ] #430 Ingest single Bag with 1 media file
- [ ] #431 Ingest single Bag with multiple media files
- [ ] #432 Ingest folder with multiple Bags
- [ ] #433 Validate checksums
- [ ] #434 Fire off Worker for Ingest task
- [ ] #435 Fire off Worker for Derivatives
- [ ] #436 Record datetime and user of successful Ingest
- [ ] #437 Figure out directory for Bags
- [ ] #438 Bulk Ingest Tasks homepage
- [ ] #439 Bulk Ingest Child Tasks pages
- [ ] #440 Figure out Review process
- OTHER

**Comment by vantuyls** [comment]
NEED TO define work types in the new repository.

**Comment by revgum** [comment]
Closed upon review of issues
