### ISSUE TITLE
[OTHER RELATED] Degree Type Drop Down Situation

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#485]
need to be able to generate drop down lists for degree level and degree name.
- [x] Pull a list of all degree level and names from dspace
- [x] Normalize the list of degree level and names 
- [x] push corrections back to dspace
- [x] both drop down lists should include an "Other" option, which pops up a text box to accept type or name that doesn't exist in the list (to accomodate new programs and degrees at OSU)
- [x] if Other is entered, the form should double check with the respective drop down to make sure the entered information isn't already in the list
- [ ] if Other is a legit new thing, notify admin to indicate need for entry into form and CVM
- [x] the Degree Field drop down list should include only the degree fields that have been granted in the past 5 years
- [x] Degree Field drop down list should update every year to represent the most recent 5 years of degree fields

**Comment by straleyb** [comment]
Last two blocked per comment in https://github.com/osulp/Scholars-Archive/issues/717

**Comment by vantuyls** [comment]
We are okay with letting the SA cache expire to update the data from ONS.

**Comment by vantuyls** [comment]
closing in favor of a number of more specific issues.
