### ISSUE TITLE
Handle and URL Mapping/Redirects

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#595]
We need to respect links and handles from DSpace for SA@OSU on Hydra. Examples of URLs and Handles we need to respect are, e.g.:

* Item Handle: http://hdl.handle.net/1957/60832
* Item Record URL: http://ir.library.oregonstate.edu/xmlui/handle/1957/60832
* Item Record Full Showpage: http://ir.library.oregonstate.edu/xmlui/handle/1957/60832?show=full
* File Download URL: http://ir.library.oregonstate.edu/xmlui/bitstream/handle/1957/60832/main.pdf?sequence=1
* Community:    (redirect to either Admin Set or Solr search results with varying facets)
* Collection:    (redirect to either Admin Set or Solr search results with varying facets)
* any admin pages or other access points?

also see: #309, #274, #275, #596

@revgum @straleyb @zhang4952 @wickr @luisgreg99 

- [ ] On ir.l.o.e, redirect traffic to handle traffic to SA on a handle controller
- [ ] The handle controller derives the original handle uri and searches SOLR for this url (ie. http://hdl.handle.net/1957/89921)  
  - [ ] If a work is found, redirect user to `#show` to that work
  - [ ] If a work is not found, show a stylish 404 error and notify SA administration of the problem

**Comment by revgum** [comment]
- [ ] On ir.l.o.e, redirect traffic to handle traffic to SA on a handle controller
- [ ] The handle controller derives the original handle uri and searches SOLR for this url (ie. http://hdl.handle.net/1957/89921)  
  - [ ] If a work is found, redirect user to `#show` to that work
  - [ ] If a work is not found, show a stylish 404 error and notify SA administration of the problem

**Comment by straleyb** [comment]
1. Handle URI will be redirected to ir.l.o.e per usual. The uri route for ir.l.o.e will be in the form `/xmlui/bitstream/handle/1957/60832/main.pdf?sequence=1`
2. ir.l.o.e will be redirected to lib-saapp1.l.o.e with the uri route being the same. (RO JOB.) e.g. `ir.l.o.e/xmlui/bitstream/handle/1957/60832/main.pdf?sequence=1 => lib-saapp1.l.o.e/xmlui/bitstream/handle/1957/60832/main.pdf?sequence=1`
3. Controller in SA handles the request in the form `/xmlui/bitstream/handle/:handle_id/:id/:filename/(:sequence)`
4. Controller extracts necessary data and builds out the handle uri in the form `hdl.handle.net/handle_id/id`
5. Use handle to query solr for work.
6. Query work from fedora to begin inspecting filesets and child works  (members)
7. Parse out file sets from the child works and bring them all into a list. 
8. Inspect filesets for matching title from the filename parameter. 
9. After proper fileset is found, redirect user to direct download link using the id from the matched fileset. 
10. If multiple filename matches exist, error report and redirect to parent work page.

**Comment by vantuyls** [comment]
@zhang4952 @straleyb @revgum are we done with this. can we close the issue?

**Comment by revgum** [comment]
Believe that we've addressed all of the routes that were initially missed, closing issue.
