### ISSUE TITLE
Metadata Application Profile Alignment

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#683]
Make changes to align the MAP with more recent conversations including:

- [x] change obligation for fields that are highlighted in shitty yellow
- [x] remove :relation property
- [ ] remove :degree_discipline
- [x] change label for realted_url per the highlighted field in the MAP
- [x] modify peerreviewed to be a yes/no drop down on the form and TRUE/FALSE on the back end
- [x] modify faceted, searchable, and visible based on those columns of the MAP - highlighted yellow are ones that need to change
- [x] when these changes are made, remove the related color coding from the MAP

See: #677, #675, #676

**Comment by vantuyls** [comment]
Obligation fields that need to be changed:
- [ ] :conferenceLocation
- [ ] :conferenceName
- [ ] :conferenceSection
- [ ] :timeRequired
- [ ] :typicalAgeRange
- [ ] :learningResourceType
- [ ] :interactivityType
- [ ] :isBasedOnUrl
- [ ] :date_collected
- [ ] :tableofcontents
- [ ] :bibliographic_citation
- [ ] :peerreviewed
- [ ] :dspace_community
- [ ] :dspace_collection
