### ISSUE TITLE
Support MetaArchive preservation

### ISSUE THREAD

**Issue by zhang4952** [osulp/Scholars-Archive#808]
MetaArchive uses OAI-PMH to harvest and preserve DSpace contents, a new approach should be implemented for SA@OSU in Hyrax:
- exporting Fedora objects as Bags
- putting Bags to a temp storage space for MetaArchive harvesting

**Comment by zhang4952** [comment]
- Ask MetaArchive harvesting DSpace before migration
- Harvesting SA@OSU around January with Bags
- Setup Bags ingestion path in between the time

**Comment by zhang4952** [comment]
We need a bulk metadata export script for Hyrax to:
1. Export the records as CSV
2. Export not only descriptive metadata, but also information such as adminset, parent/children works, and Fedora resource URIs
3. Could use a combination of SOLR search and Fedora REST API 

The Bags export script will the use the exported CSV to retrieve contents using the import-export-util plugin.

**Comment by zhang4952** [comment]
Metaarchive confirms that it had successfully crawled all the DSpace AUs by September 2.

**Comment by zhang4952** [comment]
include #963

**Comment by vantuyls** [comment]
@zhang4952 please update on this issue. I believe this is resolved (?).

**Comment by zhang4952** [comment]
Use this issue to track all the tasks for MetaArchive preservation. 

- [ ] OSU create a S3 bucket as MA staging server

- [ ] Finalize preservation workflow and Bag format with MA

- [ ] Create/revise Hyrax Bag exporting script to meet MA requests 

- [ ] Run test with MA crawler with exported Bags

- [ ] Export ETD/EESC Bags with finalized Bag export script to S3

- [ ] MA crawl and preserve Bags

**Comment by zhang4952** [comment]
include #1285

**Comment by vantuyls** [comment]
@zhang4952 update please?

**Comment by zhang4952** [comment]
related to #1726

**Comment by zhang4952** [comment]
closed via #1726
